import { ProductData } from "@/src/models/product.model";
import { cookies } from "next/headers";
import ProductGrid from "./ProductCard";  
import { Metadata } from "next";
import { ACCESS_TOKEN_KEY } from "@/src/utils/constant";

export const metadata: Metadata = {
  title: "Klepler Shop",
  description: "Generated by create next app",
};

export default async function Shop() {
  const cookieStore = cookies();
  const token = cookieStore.get(ACCESS_TOKEN_KEY);

  const result = await fetch(
    `${process.env.NEXT_PUBLIC_BASE_URL_API}/stock/product`,
    {
      method: "GET",
      headers: {
        "Content-type": "application/json",
        Authorization: `Bearer ${token?.value}`,
      },
    }
  );

  const products = (await result.json()) as ProductData[];

  return (
    <div className="w-full">
      <ProductGrid products={products} />
    </div>
  );
}
